### ISSUE TITLE
Windows Login takes too much time

### ISSUE THREAD

**Issue by DrJedikiah** [W4RH4WK/Debloat-Windows-10#118]
After running all the scripts, I can't login to my pc easily.
I'm writing my pass and hitting enter, after that windows waits, waits, waits and nothing. Password box appears again. After some time finally I can login to my account.

**Comment by W4RH4WK** [comment]
Which of the scripts have you run? Did you make any changes? Have you installed the creators update?

**Comment by DrJedikiah** [comment]
I haven't installed yet. I run the all scripts except experimental_unfuckery

**Comment by DrJedikiah** [comment]
Is there any way to reverse all effects, so then I can try one by one to find which one makes problem

**Comment by W4RH4WK** [comment]
No, unfortunately not (this is clearly stated in the README and also a reason why I only recommend doing this on a fresh installation). You can go over the code line by line and re-enabled the things that have been disabled.

The first thing you might want to try is to re-enable all of the services, clear all added entries from `%windir%\System32\drivers\etc\hosts`, and disable the added firewall rule. A long delay on the login screen may be caused by a timeout of one of the subsystems. Yet this is the first time such an issue is reported back to me.

**Comment by W4RH4WK** [comment]
Did any of that help?

**Comment by W4RH4WK** [comment]
I just run the current set of scripts on a freshly installed (and updated) VM, after that, and a reboot the initial user login took about 8 seconds. The password box does not appear again.

**Comment by majkinetor** [comment]
What event viewer shows ?
Does it make a difference if you keep pressing esc during the login ?

**Comment by DrJedikiah** [comment]
Sorry for late reply. I'm very busy these days, I'll try ASAP and thanks for helping me.

**Comment by DrJedikiah** [comment]
![image](https://user-images.githubusercontent.com/12988451/26993028-1248c396-4d6a-11e7-9161-d210e94f9d3c.png)
Event viewer shows like this, and pressing esc didn't worked :(
I'm gonna try starting all services back

**Comment by W4RH4WK** [comment]
Did you have any success with re-enabling services?
