### ISSUE TITLE
Feature request: Windows 10 LTSC debloat mode

### ISSUE THREAD

**Issue by MikaelPorttila** [W4RH4WK/Debloat-Windows-10#223]
Hi,
My guess is that some of these scripts are still applicable for the LTSC version of Windows 10, would it be possible to call the scripts with a --ltsc parameter so only needed scripts would run or are the scripts already designed so the wouldn't run if not needed?

**Comment by W4RH4WK** [comment]
Officially speaking, LTSC is not supported.

The scripts behave in a *best effort* fashion. Errors, like removing applications that aren't even installed, are simply ignored. Therefore, you should be able to use them alongside LTSC.

As always, only use them on a fresh installation, and test your system before using it for production.

Let me know if any of the script's commands cause issues with LTSC. I probably won't fix them, because LTSC is not officially supported, but I can add a comment so people know what to look out for.
