### ISSUE TITLE
Sling not removed.

### ISSUE THREAD

**Issue by bradleysepos** [W4RH4WK/Debloat-Windows-10#232]
As the title suggests, on a fully up to date system, running the remove default apps script leaves behind Sling.

**Comment by W4RH4WK** [comment]
Hey there. I don't have that app installed on my test system and cannot install it via the Windows Store (probably due to regional restrictions). Can you provide me the identifier of the app. Running the following command in PowerShell should do the trick, given Sling was not yet removed.

    Get-AppxPackage | select Name | Select-String sling

If this outputs nothing, please try this:

    Get-AppxPackage | select Name

I should probably recognize the app name from this.

**Comment by bradleysepos** [comment]
`SlingTVLLC.SlingTV` should do it. 😸

**Comment by W4RH4WK** [comment]
Thank you very much.
