### ISSUE TITLE
disabling ShellExperienceHost issues

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [W4RH4WK/Debloat-Windows-10#250]
Hello, this is more an info than an issue.
i had windows 10 version 1909 and i run all Debloat-Windows-10 scripts and as a result i had some problems: 
- right clicking on taskbar apps doesn't show the small `close windows; pin/unpin to taskbar ...` panel. 
- clicking on the wifi taskbar icon doesn't display the panel.
- not able to move from a directory to another inside wsl 1 (cd not working).

after investigation i found that disabling ShellExperienceHost caused that [`disable-ShellExperienceHost.bat `]

so renaming `%windir%\SystemApps\ShellExperienceHost_cw5n1h2txyewy.bak` to `%windir%\SystemApps\ShellExperienceHost_cw5n1h2txyewy` then restarting the computer resolved all those issues.

so hope that people try to reproduce that & if confirmed then we should discuss about keeping disable-ShellExperienceHost.bat or adding an alert about that in the docs

**Comment by W4RH4WK** [comment]
Thanks for the heads up. It sounds reasonable that these issues are caused by the ShellExperienceHost app / service. I've added a warning to the corresponding script.

**Comment by azev** [comment]
I thought maybe replacing `ShellExperienceHost.exe `with `calc.exe` or maybe another dumb .exe file that does nothing. Maybe then the mentioned problems won't happen.

**Comment by W4RH4WK** [comment]
@azev I doubt that replacing the exe with another would solve the mentioned issues. It's more likely that the underlying implementation requires the exe through some means. However, if you can verify that renaming the folder breaks things and simply replacing the exe does not, I'd reconsider it. Although, it feels like a hack that may lead to things breaking later down the line.

**Comment by azev** [comment]
@W4RH4WK Hi mate.
Indeed you are correct. We would have to hack (hex edit) `ShellExperienceHost.exe` properly so it would sit quietly without eating RAM or using the internet, or collecting data.

**Comment by OrthodoxWindows** [comment]
I managed to solve most of the problems posed by the disabling of ShellExperienceHost 👍 

ShellExpreienceHostexe is the process that manages most immersive/UWP applets ; The solution is therefore to replace them with non immersive/UWP equivalents.

To this day, here are the solution I found :

Use the Windows 7 power flyout or BatteryMod
Use the Windows 7 sound panel (https://github.com/valinet/ExplorerPatcher/wiki/All-features#sound) or any other alternative sound flyout
Use the Windows 7 clock flyout (https://github.com/valinet/ExplorerPatcher/wiki/All-features#clock)
Use PeNetworkManager instead of the immersive network flyout [winclassic.boards.net/thread/1061/penetwork-classic-mod](https://winclassic.boards.net/thread/1061/penetwork-classic-mod)
Use osk.exe instead of the immersive visual keyboard
Use the Standard menu option from the "right click" box in 7+ taskbar tweaker
Use the ExplorerPatcher weather widget instead of the "news and field of interest" widget
Use the balloon tooltip notification (https://winaero.com/winaero-tweaker/)
Use ExplorerPatcher simple window switcher (https://github.com/valinet/ExplorerPatcher/wiki/All-features#simple-window-switcher) or NT window switcher (https://github.com/valinet/ExplorerPatcher/wiki/All-features#windows-nt-switcher)

For these problems, i have no solution for the moment :

The capital / lowercase indication works, but does not appear
The Windows Ink workplace does not work
The notification center does not work
The emoji picker does not work

**Comment by swierku123** [comment]
czy dawac do autostartu
