### ISSUE TITLE
remove-default-apps.ps1 - is it possible to remove content delivery tiles?

### ISSUE THREAD

**Issue by daleallenc** [W4RH4WK/Debloat-Windows-10#52]
I've found that Minecraft: Windows 10 Edition Beta, Adobe Photoshop Express, and Flipboard fall under some kind of content delivery system and can't be removed with script. This is what they look like when exported:

SecondaryTile AppUserModelID="Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy!App" TileID="PreInstalled.DefaultStartLayout2.2" DisplayName="Minecraft: Windows 10 Edition Beta" ...(clipped)

SecondaryTile AppUserModelID="Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy!App" TileID="PreInstalled.DefaultStartLayout1.2" DisplayName="Adobe Photoshop Express" ...(clipped)

SecondaryTile AppUserModelID="Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy!App" TileID="PreInstalled.DefaultStartLayout1.3" DisplayName="Flipboard" ... (clipped)

[default-start-layout.txt](https://github.com/W4RH4WK/Debloat-Windows-10/files/343954/default-start-layout.txt)

**Comment by W4RH4WK** [comment]
I think it should be possible to remove the tiles from the start menu, this may not be adequate for the `remove-default-apps.ps1` but fits in one of the optimization scripts. I'll look at this a little bit later when I have more time. Simply unpin them for now or replace your start menu with something more useful like classic shell.

**Comment by W4RH4WK** [comment]
the `optimize-user-interface.ps1` script will remove all start menu tiles, those content delivery tiles should be gone too.

**Comment by bittin** [comment]
cool will look into that when we are installing Windows 10 in another
computer lab at work in August something more we have use for :)

**Comment by Daystrom256** [comment]
Hi, could this issue be re-opened? 

I tried the latest version of the script and it still won't remove some tiles.  I checked the command that removes all ties, it seems to only check installed apps to unpin them if they are pinned.  

These leftover tiles are something different, like web shortcuts stored in wherever MS has chosen to store this info.  Pre-Windows 10 it would have been a folder somewhere you could delete the link from.  export-startlayout via powershell shows:

```
<start:SecondaryTile AppUserModelID="Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy!App" TileID="PreInstalled.DefaultStartLayout2.2" DisplayName="Minecraft: Windows 10 Edition Beta" ...(clipped)
<start:SecondaryTile AppUserModelID="Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy!App" TileID="PreInstalled.DefaultStartLayout1.2" DisplayName="PicsArt - Photo Studio" ...(clipped)
<start:SecondaryTile AppUserModelID="Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy!App" TileID="PreInstalled.DefaultStartLayout1.3" DisplayName="Duolingo - Learn Languages for Free" ...(clipped)

```

**Comment by W4RH4WK** [comment]
Sure,I have seen this recently happening with the anniversary edition, but haven't found a better we to solve this yet.

**Comment by Daystrom256** [comment]
Related to these 3rd party tiles...

_Feature enhancement_
Have remove-default-apps.ps1 delete all reg_dword entries in this registry key:
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContenetDeliveryManager\SuggestedApps
(Twitter came back with a windows update after being uninstalled, I suspect because it was in this list of suggested apps?)

_Background info_
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContenetDeliveryManager REG_DWORD SystemPaneSuggestionsEnabled set to 0 to disable and corresponds to settings > Personalization > Start > "Occasionally show suggestions in start"
Source: http://www.winhelponline.com/blog/how-to-disable-start-menu-ads-or-suggestions-in-windows-10/

Listed nearby in registry are 5 apps, 3 of which are the ones I'm trying to get rid of the tiles.  See:  HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContenetDeliveryManager\SuggestedApps
Appropriate settings in this area of the registry will likely prevent these zombies from coming back from the dead as Twitter did.

**Comment by brad-x** [comment]
I've also been setting the 'DisableWindowsConsumerFeatures' DWORD to a value of 1 under HKLM\Software\Policies\Microsoft\Windows\CloudContent. More info at: 

https://winpeguy.wordpress.com/2015/12/06/win10-start-menu-junk-and-candy-crush-soda-saga/

**Comment by W4RH4WK** [comment]
You may not be pleased to hear this, but I ditched the official startmenu, I stated my reasons [in the readme](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/README.md#startmenu).

Please use something more sophisticated.
