### ISSUE TITLE
File Explorer doesn't open

### ISSUE THREAD

**Issue by caycehouse** [W4RH4WK/Debloat-Windows-10#58]
When I try to launch File Explorer I am greeted by a explorer.exe unspecified error popup.

**Comment by W4RH4WK** [comment]
Can you be a bit more specific on which files you ran, whether you did any changes to them and whether this is reproducible.

**Comment by W4RH4WK** [comment]
Double check this setting in case you installed the anniversary update.

![capture](https://cloud.githubusercontent.com/assets/328798/17407660/76e7c0d6-5a68-11e6-8441-41d4246b67e0.PNG)

**Comment by zandersays** [comment]
This can be fixed by changing 
`sp "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "LaunchTo" 0`
to
`sp "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "LaunchTo" 1`

as the two options are:
- 1 for "This PC"
- 2 for "Quick Access"

0 breaks explorer unless you open to a specific folder IE "C:/"

**Comment by W4RH4WK** [comment]
Thanks @zandersays, I patched the related script.
